### ISSUE TITLE
Adding curveTypes

### ISSUE THREAD

**Issue by Luke-kb** [zsteinkamp/m4l-ChiasticSlide#2]
Hi Zack, thanks for making this plugin!
Something that I think would make it super versatile for myself and many folks would be the option to choose different curve shapes such as those that the ableton crossfader offers. eg _Constant Power, Dipped, Intermediate, Slow Fade, Fast Cut, Transition_

Would you be interested in this?

I've had a go but haven't got much experience with max and am having issues linking the functions up to the UI. 
here is some modified code (and a few new functions).

keen to see what you think

```
function lerp(val, min, max, curve) {
  var ret;
  switch (curve) {
    case 0.5: // DIPPED
      ret = Math.min(min, max) + (Math.abs(max - min) * Math.sqrt(val));
      break;
    case 1.5: // INTERMEDIATE
      ret = Math.min(min, max) + (Math.abs(max - min) * Math.pow(val, 1.5));
      break;
    case 2: // SLOW_FADE
      ret = Math.min(min, max) + (Math.abs(max - min) * Math.pow(val, 2));
      break;
    case 0.25: // FAST_CUT
      ret = Math.min(min, max) + (Math.abs(max - min) * Math.pow(val, 0.25));
      break;
    case 3: // TRANSITION
      ret = Math.min(min, max) + (Math.abs(max - min) * Math.pow(val, 3));
      break;
    default: // CONSTANT_POWER
      ret = Math.min(min, max) + (Math.abs(max - min) * val);
  }
  return ret;
}

var CurveType = {
  CONSTANT_POWER: 0,
  DIPPED: 1,
  INTERMEDIATE: 2,
  SLOW_FADE: 3,
  FAST_CUT: 4,
  TRANSITION: 5
};

const msg_int = (index) => {
  var curveType;
  switch (index) {
    case 0:
      curveType = CurveType.CONSTANT_POWER;
      break;
    case 1:
      curveType = CurveType.DIPPED;
      break;
    case 2:
      curveType = CurveType.INTERMEDIATE;
      break;
    case 3:
      curveType = CurveType.SLOW_FADE;
      break;
    case 4:
      curveType = CurveType.FAST_CUT;
      break;
    case 5:
      curveType = CurveType.TRANSITION;
      break;
    default:
      curveType = CurveType.CONSTANT_POWER;
  }
  changeCurve(curveType);
}

const changeCurve = (curveType) => {
  switch (curveType) {
    case CurveType.CONSTANT_POWER:
      state.curve = 1;
      break;
    case CurveType.DIPPED:
      state.curve = 0.5;
      break;
    case CurveType.INTERMEDIATE:
      state.curve = 1.5;
      break;
    case CurveType.SLOW_FADE:
      state.curve = 2;
      break;
    case CurveType.FAST_CUT:
      state.curve = 0.25;
      break;
    case CurveType.TRANSITION:
      state.curve = 3;
      break;
    default:
      state.curve = 1;
  }
  draw();
  updateVolumes();
}
```

**Comment by zsteinkamp** [comment]
Thanks @Luke-kb for the suggestion and examples!
I was not familiar with the crossfader presets in Live before your message.

So it looks like you're looking for some presets for the "Curve" dial that's in the device? Since with the curve dial set to the values you've listed, mathematically it should be the same as what you listed.

The `**` operator in JS is the same as Math.pow(), e.g.

```
2 ** 3
=> 8
Math.pow(2, 3)
=> 8
```

So the existing lerp() method will provide the same output as your function for the same curve values.
```
function lerp(val: number, min: number, max: number, curve: number) {
  const ret = Math.min(min, max) + (Math.abs(max - min) * (val ** curve))
}
```


So do you think that instead of a continuous Curve dial the device should have some button presets? Or perhaps the preset buttons could just set the curve dial to a certain value, e.g. click "Slow Fade" and the knob is set to 0.25?

**Comment by Luke-kb** [comment]
Thanks @zsteinkamp -  you are right! your lerp function already covers all the curve shapes, I misunderstood what was going on. I think a dropdown menu or preset button for the curve knob is a good idea :) 

I can still hear a difference between the ableton crossfader and chiasticSlide, and from a bit more research I think the missing element is the "power level" between the 2 signals during the crossfade event.

Apparently using a trig function ensures the sum of the squares of the signal volumes remains constant which avoids a perceived dip in volume when using the linear crossfade function?

```
function constantPowerCrossfade(position) {
    const x = Math.max(0, Math.min(1, position));
    const volumeA = Math.cos(x * Math.PI / 2);
    const volumeB = Math.sin(x * Math.PI / 2);
    return { volumeA, volumeB };
}
```

I'm totally sure of the functions that are being used for the others, but the graphic from the ableton manual gives a hint (my experience in this area is very little!)

[crossfader_curves.pdf](https://github.com/user-attachments/files/17964815/crossfader_curves.pdf)

What do you think?

**Comment by zsteinkamp** [comment]
Oh this is great! Thanks @Luke-kb. I love that someone at Ableton was this passionate about crossfaders to explain it. Also awesome they had the idea to add three keyboard shortcuts to the crossfader. I had no idea!

And thanks for sending the code. I tried it out and I don't think it's doing what you think it's doing :) The constantPowerCrossfade needs to take the value as its input, not the curve. In fact, in that model the curve maybe doesn't really even have a place?

I'm trying out a constant power option that adjusts the volume like this:
```diff
@@ -173,6 +179,10 @@ function calcVolumeAt(inPos) {
         delta = 360 - delta;
     }
     var volume = Math.max(1 - (delta / halfW), 0);
+    // constant power volume adjustment
+    if (state.constantPower) {
+        volume = Math.sin(volume * Math.PI / 2);
+    }
     return lerp(volume, state.minVol, state.maxVol, state.curve);
 }
```

It does make a difference in terms of where a real "constant power" setting is. For example, I set up a group of 6 tracks playing the same sample. I then set up a Chiastic Slide on the group track with an LFO modulating its "Direction" parameter, so it just runs in a circle (ramp up LFO doing the modulating).

I set the width to 120, since there were 6 subtracks. 360/6 * 2 = 120

With Constant Power engaged, I get a loudness that is consistent around the circle and also the same loudness as a single instance of the original sample playing at Curve=0.64. With Constant Power off (Linear) then setting the Curve to 0.32 gets back to level.

I'm a little out of my depth when it comes to the correctness of just using the `sin` side of the function you sent, but looking at the curves of sin and cos and listening to how the faders react, that seems to be the better choice.

You can download the version of the device I was testing with here:
https://steinkamp.us/dropbox/ChiasticSlide-v7-ConstantPower.amxd

Curious what your thoughts are!

**Comment by zsteinkamp** [comment]
Woohoo! Thanks @Luke-kb :)

I just released v8 which fixes an automation bug, so you may want to update.
